import 'package:flutter/material.dart';
import '../../models/profile.dart';
import '../../state/profile_store.dart';
import '../navigation/app_shell.dart';

class QuestionnaireScreen extends StatefulWidget { final ProfileStore store; const QuestionnaireScreen({super.key, required this.store}); @override State<QuestionnaireScreen> createState() => _QuestionnaireState(); }
class _QuestionnaireState extends State<QuestionnaireScreen> {
  int step = 0; final p = UserProfile(); final info = UserPersonalInfo(); final name = TextEditingController(); final age = TextEditingController(); final height = TextEditingController(); final start = TextEditingController(); final target = TextEditingController(); final frequency = TextEditingController(); final duration = TextEditingController(); final custom = TextEditingController(); final injury = TextEditingController(); final surgery = TextEditingController();
  final titles = const ['About You', 'Your Goal', 'Lifestyle', 'Exercise Routine', 'Equipment', 'Physical Considerations', 'Review'];
  final goals = const ['Lose weight', 'Build muscle', 'Improve fitness', 'Improve posture', 'Maintain health']; final lifestyles = const ['Mostly sedentary', 'Lightly active', 'Moderately active', 'Very active']; final habits = const ['Dancing', 'Swimming', 'Running', 'Badminton', 'Basketball', 'Gym', 'Pilates', 'Yoga', 'Other']; final locations = const ['Home', 'Gym', 'Swimming pool', 'Pilates studio', 'Outdoors', 'Other']; final equipment = const ['No equipment', 'Dumbbells', 'Resistance band', 'Yoga mat', 'Kettlebell', 'Treadmill', 'Stationary bike', 'Pull-up bar', 'Other'];
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: Text('Getting started · ${step + 1}/7')), body: Padding(padding: const EdgeInsets.all(20), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [LinearProgressIndicator(value: (step + 1) / 7), const SizedBox(height: 24), Text(titles[step], style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.bold)), const SizedBox(height: 18), Expanded(child: SingleChildScrollView(child: _content())), Row(children: [if (step > 0) Expanded(child: OutlinedButton(onPressed: () => setState(() => step--), child: const Text('Back'))), if (step > 0) const SizedBox(width: 12), Expanded(child: FilledButton(onPressed: _next, child: Text(step == 6 ? 'Continue to Home' : 'Continue')))])])));
  Widget _content() { switch (step) { case 0: return Column(children: [_field(name, 'Name', false), _field(age, 'Age', true), _field(height, 'Height (cm)', true), _field(start, 'Initial weight (kg)', true), _field(target, 'Target weight (kg)', true), _choice('Sex', ['Female', 'Male', 'Other'], p.sex, (v) => p.sex = v)]); case 1: return Column(children: [_choice('Goal', goals, p.goal, (v) => p.goal = v), TextField(controller: custom, decoration: const InputDecoration(labelText: 'Custom goal (optional)'))]); case 2: return _choice('Lifestyle', lifestyles, p.lifestyle, (v) => p.lifestyle = v); case 3: return Column(children: [_field(frequency, 'Times per week', true), _field(duration, 'Minutes per session', true), _choice('Usual exercise', habits, p.exerciseHabit, (v) => p.exerciseHabit = v), _choice('Exercise location', locations, p.exerciseLocation, (v) => p.exerciseLocation = v)]); case 4: return _multiChoice('Equipment available', equipment, info.availableEquipment); case 5: return Column(children: [const Align(alignment: Alignment.centerLeft, child: Text('Optional — skip if not applicable.')), const SizedBox(height: 12), TextField(controller: injury, maxLines: 3, decoration: const InputDecoration(labelText: 'Current or previous injuries')), TextField(controller: surgery, maxLines: 3, decoration: const InputDecoration(labelText: 'Relevant surgery history'))]); default: return _review(); } }
  Widget _field(TextEditingController c, String label, bool number, {ValueChanged<String>? onChanged}) => Padding(padding: const EdgeInsets.only(bottom: 12), child: TextField(controller: c, keyboardType: number ? TextInputType.number : TextInputType.text, onChanged: onChanged, decoration: InputDecoration(labelText: label)));
  Widget _choice(String label, List<String> options, String selected, ValueChanged<String> set) => Padding(padding: const EdgeInsets.only(bottom: 12), child: DropdownButtonFormField<String>(value: selected.isEmpty ? null : selected, decoration: InputDecoration(labelText: label), items: options.map((x) => DropdownMenuItem(value: x, child: Text(x))).toList(), onChanged: (v) { if (v != null) setState(() => set(v)); }));
  Widget _multiChoice(String label, List<String> options, List<String> selected) => Wrap(spacing: 8, children: options.map((x) => FilterChip(label: Text(x), selected: selected.contains(x), onSelected: (on) => setState(() { on ? selected.add(x) : selected.remove(x); }))).toList());
  Widget _review() => Column(children: [Text('Please check your information before continuing.', style: Theme.of(context).textTheme.bodyLarge), const SizedBox(height: 12), ...[p.name, '${p.age} years · ${p.sex}', '${p.heightCm} cm · ${p.startWeightKg} kg → ${p.targetWeightKg} kg', p.goal, p.lifestyle, '${p.exerciseFrequencyPerWeek} times/week · ${p.exerciseDurationMinutes} minutes', p.exerciseHabit, p.exerciseLocation, 'Equipment: ${info.availableEquipment.join(', ')}'].map((x) => ListTile(title: Text(x.isEmpty ? 'Not provided' : x)))]);
  void _next() { if (step == 0) { p.name = name.text.trim(); p.age = int.tryParse(age.text) ?? 0; p.heightCm = double.tryParse(height.text) ?? 0; p.startWeightKg = double.tryParse(start.text) ?? 0; p.targetWeightKg = double.tryParse(target.text) ?? 0; if (p.name.isEmpty || p.age <= 0 || p.heightCm <= 0 || p.startWeightKg <= 0 || p.targetWeightKg <= 0 || p.sex.isEmpty) return _error('Please complete all required fields.'); } if (step == 1) { if (custom.text.trim().isNotEmpty) p.goal = custom.text.trim(); if (p.goal.isEmpty) return _error('Please choose a goal.'); } if (step == 2 && p.lifestyle.isEmpty) return _error('Please choose your lifestyle.'); if (step == 3) { p.exerciseFrequencyPerWeek = int.tryParse(frequency.text) ?? 0; p.exerciseDurationMinutes = int.tryParse(duration.text) ?? 0; if (p.exerciseFrequencyPerWeek < 0 || p.exerciseDurationMinutes < 0 || p.exerciseHabit.isEmpty || p.exerciseLocation.isEmpty) return _error('Please complete your exercise routine.'); } if (step == 5) { if (injury.text.trim().isNotEmpty) info.injuries = [injury.text.trim()]; if (surgery.text.trim().isNotEmpty) info.surgeryHistory = [surgery.text.trim()]; } if (step == 6) { widget.store.save(profile: p, personalInfo: info); Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => AppShell(store: widget.store))); } else setState(() => step++); }
  void _error(String message) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(message)));
}
